### ISSUE TITLE
[BUG] Missing module manifest

### ISSUE THREAD

**Issue by DevConFox** [p4535992/foundryvtt-potion-crafting-and-gathering#1]
**Module Version:** v0.5.2
Currently, the provided URL gives an error when trying to install the module via Foundry:

```
Uncaught (in promise) Error: Unable to load valid module manifest data from "https://raw.githubusercontent.com/p4535992/foundryvtt-potion-crafting-and-gathering/master/module.json"
No module manifest found at https://raw.githubusercontent.com/p4535992/foundryvtt-potion-crafting-and-gathering/master/module.json
    at Module.installPackage (file:///home/ubuntu/foundry/resources/app/dist/packages/views.mjs:1:1692)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SetupView.handlePost (file:///home/ubuntu/foundry/resources/app/dist/server/views/setup.mjs:1:2108)
```

**Foundry Version:** 
11.308

**Comment by p4535992** [comment]
i have miss type the readme `https://raw.githubusercontent.com/p4535992/foundryvtt-potion-crafting-and-gathering/master/src/module.json`
